version: '3.8'

services:
  server:
    build: 
      context: ./server
      args:
        - NODE_ENV=development
    command: >
      sh -c "cd server ; npm install ; npm run dev"
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chatter
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - chatter-network

  client:
    build: 
      context: ./client
      args:
        - NODE_ENV=development
    command: >
      sh -c "cd client ; npm install ; npm start"
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - chatter-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - chatter-network

networks:
  chatter-network:
    driver: bridge

volumes:
  mongodb_data: